### ISSUE TITLE
smart_alarm display errors

### ISSUE THREAD

**Issue by mjf2708** [fgebhart/smart_alarm#1]
I'm continually getting errors when I try to run smart_alarm/tests/display_time.py:

pi@raspberrypi:~/smart_alarm/tests $ python display_time.py
Traceback (most recent call last):
  File "display_time.py", line 9, in <module>
    display.begin()
  File "build/bdist.linux-armv6l/egg/Adafruit_LED_Backpack/HT16K33.py", line 53, in begin
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/I2C.py", line 127, in writeList
  File "build/bdist.linux-armv6l/egg/Adafruit_PureIO/smbus.py", line 274, in write_i2c_block_data
IOError: [Errno 5] Input/output error

I've followed instructions, installed all packages, and other functions (e.g., sound) work OK.

**Comment by fgebhart** [comment]
make sure your i2c is enabled via `sudo raspi-config` -> `interfacing options`.

If this doesn't help, you have to check through your wiring one more time. Seems like it is not connected properly, [like pointed out here](https://github.com/adafruit/Adafruit_Python_CharLCD/issues/19).

Also consider the [adafruit tutorial](https://learn.adafruit.com/14-segment-alpha-numeric-led-featherwing/) for more information about the alphanumeric display.

**Comment by mjf2708** [comment]
Thanks - this was a simple wiring problem (was working, one wire became disconnected!)
